-- migrate:up

-- Activity event types
CREATE TYPE activity_type AS ENUM (
    'query',          -- User query/search
    'domain_change',  -- Domain focus change
    'swarm_run',      -- Swarm analysis executed
    'tda_compute',    -- TDA computation
    'projection',     -- Projection to grid
    'kb_create',      -- KB entry created
    'kb_update',      -- KB entry updated
    'command',        -- CLI command executed
    'startup',        -- App started
    'shutdown'        -- App closed
);

-- Activity events log
CREATE TABLE activity_events (
    id SERIAL PRIMARY KEY,
    event_type activity_type NOT NULL,
    profile_name TEXT,  -- Which profile was active
    domain TEXT,        -- Domain context if applicable
    details JSONB DEFAULT '{}',
    -- Details examples:
    -- query: {"query": "...", "results_count": 10}
    -- swarm_run: {"agents": 7, "tokens": 6360, "latency_ms": 24000}
    -- command: {"command": "/swarm", "args": "..."}
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_activity_events_type ON activity_events(event_type);
CREATE INDEX idx_activity_events_profile ON activity_events(profile_name);
CREATE INDEX idx_activity_events_created ON activity_events(created_at DESC);
CREATE INDEX idx_activity_events_domain ON activity_events(domain) WHERE domain IS NOT NULL;

-- Daily summaries (generated by daily summary agent)
CREATE TABLE daily_summaries (
    id SERIAL PRIMARY KEY,
    summary_date DATE NOT NULL UNIQUE,
    profile_name TEXT,
    content TEXT NOT NULL,         -- Markdown summary
    highlights JSONB DEFAULT '[]', -- Key points array
    metrics JSONB DEFAULT '{}',    -- Aggregated metrics
    -- Metrics examples:
    -- {"queries": 15, "swarm_runs": 3, "kb_entries": 5, "total_tokens": 12000}
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    generator_model TEXT           -- Which model generated this
);

CREATE INDEX idx_daily_summaries_date ON daily_summaries(summary_date DESC);

-- View for today's activity count by type
CREATE VIEW activity_today AS
SELECT
    event_type,
    COUNT(*) as count,
    MAX(created_at) as last_at
FROM activity_events
WHERE created_at >= CURRENT_DATE
GROUP BY event_type;

-- View for this week's activity summary
CREATE VIEW activity_this_week AS
SELECT
    DATE(created_at) as day,
    event_type,
    COUNT(*) as count
FROM activity_events
WHERE created_at >= DATE_TRUNC('week', CURRENT_DATE)
GROUP BY DATE(created_at), event_type
ORDER BY day DESC, event_type;

-- migrate:down

DROP VIEW IF EXISTS activity_this_week;
DROP VIEW IF EXISTS activity_today;
DROP TABLE IF EXISTS daily_summaries;
DROP TABLE IF EXISTS activity_events;
DROP TYPE IF EXISTS activity_type;
