"""Situational Awareness for Gaius startup and ongoing operation.

Generates reports based on:
- Recent KB entries (within emphasis_hours)
- Activity summaries (today, yesterday, week)
- Domain state and topological features
- Time horizons (tactical, strategic, secular)

Usage:
    from gaius.awareness import generate_startup_report

    report = await generate_startup_report()
    print(report.to_markdown())
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from ..core.config import get_config, AwarenessConfig
from ..core.activity import ActivitySummary


@dataclass
class RecentEntry:
    """A recent KB entry for awareness."""

    title: str
    path: str
    created_at: datetime
    domain: str | None = None
    summary: str | None = None


@dataclass
class TimeHorizon:
    """Activity and entries within a time horizon."""

    name: str  # "emphasis", "tactical", "strategic", "secular"
    description: str
    start: datetime
    end: datetime
    entry_count: int = 0
    key_topics: list[str] = field(default_factory=list)
    notable_entries: list[RecentEntry] = field(default_factory=list)


@dataclass
class SituationalReport:
    """Complete situational awareness report."""

    generated_at: datetime
    profile: str
    current_domain: str | None = None

    # Time horizons
    emphasis: TimeHorizon | None = None  # Last N hours
    tactical: TimeHorizon | None = None  # Last N days
    strategic: TimeHorizon | None = None  # Last N weeks/months
    secular: TimeHorizon | None = None  # Long-term trends

    # Activity summary
    activity_today: ActivitySummary | None = None
    activity_yesterday: ActivitySummary | None = None
    activity_week: ActivitySummary | None = None

    # System state
    kb_total_entries: int = 0
    vector_store_count: int = 0
    last_tda_run: datetime | None = None
    pending_jobs: int = 0

    # Insights (generated by LLM if available)
    key_insights: list[str] = field(default_factory=list)
    recommended_focus: str | None = None

    def to_markdown(self) -> str:
        """Format report as markdown."""
        lines = ["# Situational Awareness Report"]
        lines.append(f"*Generated: {self.generated_at.strftime('%Y-%m-%d %H:%M')}*")
        lines.append(f"*Profile: {self.profile}*")

        if self.current_domain:
            lines.append(f"*Domain: {self.current_domain}*")

        lines.append("")

        # Emphasis horizon (most urgent)
        if self.emphasis and self.emphasis.entry_count > 0:
            lines.append(f"## {self.emphasis.name}: {self.emphasis.description}")
            lines.append(f"**{self.emphasis.entry_count} entries** in the last {self._hours_ago(self.emphasis.start)} hours")
            if self.emphasis.notable_entries:
                lines.append("\n### Recent:")
                for entry in self.emphasis.notable_entries[:5]:
                    lines.append(f"- **{entry.title}**")
                    if entry.summary:
                        lines.append(f"  {entry.summary[:100]}...")
            lines.append("")

        # Activity summary
        if self.activity_today:
            lines.append(self.activity_today.to_markdown())
            lines.append("")

        if self.activity_yesterday and self.activity_yesterday.total_events > 0:
            lines.append(self.activity_yesterday.to_markdown())
            lines.append("")

        # Key insights
        if self.key_insights:
            lines.append("## Key Insights")
            for insight in self.key_insights:
                lines.append(f"- {insight}")
            lines.append("")

        # Recommended focus
        if self.recommended_focus:
            lines.append("## Recommended Focus")
            lines.append(self.recommended_focus)
            lines.append("")

        # System state
        lines.append("## System State")
        lines.append(f"- KB entries: {self.kb_total_entries}")
        lines.append(f"- Vector store: {self.vector_store_count} embeddings")
        if self.last_tda_run:
            lines.append(f"- Last TDA: {self.last_tda_run.strftime('%H:%M')}")
        if self.pending_jobs:
            lines.append(f"- Pending jobs: {self.pending_jobs}")

        return "\n".join(lines)

    def to_compact(self) -> str:
        """Format as compact single-line status."""
        parts = []

        if self.emphasis and self.emphasis.entry_count > 0:
            parts.append(f"{self.emphasis.entry_count} recent")

        if self.activity_today:
            if self.activity_today.queries:
                parts.append(f"{self.activity_today.queries}q")
            if self.activity_today.swarm_runs:
                parts.append(f"{self.activity_today.swarm_runs}s")

        parts.append(f"{self.kb_total_entries} KB")

        return " | ".join(parts)

    def _hours_ago(self, dt: datetime) -> int:
        """Calculate hours since datetime."""
        return int((datetime.now() - dt).total_seconds() / 3600)


class SituationalAwareness:
    """Generates situational awareness reports.

    Combines KB state, activity tracking, and optional LLM synthesis
    to provide context-rich startup and on-demand reports.
    """

    def __init__(self, config: AwarenessConfig | None = None):
        """Initialize situational awareness.

        Args:
            config: Awareness configuration. If None, uses global config.
        """
        if config is None:
            config = get_config().awareness
        self.config = config

    async def generate_report(
        self,
        profile: str = "default",
        current_domain: str | None = None,
        include_insights: bool = False,
    ) -> SituationalReport:
        """Generate a situational awareness report.

        Args:
            profile: Active profile name
            current_domain: Current domain focus
            include_insights: If True, use LLM to generate insights

        Returns:
            SituationalReport with current state
        """
        now = datetime.now()

        report = SituationalReport(
            generated_at=now,
            profile=profile,
            current_domain=current_domain,
        )

        # Build time horizons
        report.emphasis = await self._build_horizon(
            "Emphasis",
            f"Last {self.config.emphasis_hours} hours",
            now - timedelta(hours=self.config.emphasis_hours),
            now,
        )

        report.tactical = await self._build_horizon(
            "Tactical",
            f"Last {self.config.default_horizon_days} days",
            now - timedelta(days=self.config.default_horizon_days),
            now,
        )

        # Get activity summaries
        try:
            from ..core.activity import get_activity_tracker

            tracker = get_activity_tracker()
            report.activity_today = await tracker.get_today()
            report.activity_yesterday = await tracker.get_yesterday()
            report.activity_week = await tracker.get_this_week()
        except Exception as e:
            raise RuntimeError(
                f"Failed to get activity summaries: {e}\n"
                "Guru Meditation: #SA.00000001.ACTIVITY\n"
                "Check: Activity tracker initialization"
            ) from e

        # Get KB stats
        report.kb_total_entries = await self._count_kb_entries()

        # Get vector store stats
        report.vector_store_count = await self._count_vector_store()

        # Generate insights if requested
        if include_insights:
            report.key_insights = await self._generate_insights(report)
            report.recommended_focus = await self._generate_focus(report)

        return report

    async def _build_horizon(
        self,
        name: str,
        description: str,
        start: datetime,
        end: datetime,
    ) -> TimeHorizon:
        """Build a time horizon with entries."""
        horizon = TimeHorizon(
            name=name,
            description=description,
            start=start,
            end=end,
        )

        # Get recent KB entries
        entries = await self._get_recent_entries(start, end)
        horizon.entry_count = len(entries)
        horizon.notable_entries = entries[:10]

        # Extract key topics from titles
        if entries:
            topics = self._extract_topics([e.title for e in entries])
            horizon.key_topics = topics[:5]

        return horizon

    async def _get_recent_entries(
        self,
        start: datetime,
        end: datetime,
    ) -> list[RecentEntry]:
        """Get KB entries created within time range."""
        entries = []

        config = get_config()
        kb_path = config.kb.current_path

        if not kb_path.exists():
            return entries

        # Scan KB for recent markdown files
        try:
            for md_file in kb_path.rglob("*.md"):
                stat = md_file.stat()
                mtime = datetime.fromtimestamp(stat.st_mtime)

                if start <= mtime <= end:
                    # Read first line as title
                    title = md_file.stem.replace("-", " ").replace("_", " ").title()
                    try:
                        content = md_file.read_text()
                        first_line = content.split("\n")[0].strip()
                        if first_line.startswith("#"):
                            title = first_line.lstrip("#").strip()
                    except Exception as e:
                        raise RuntimeError(
                            f"Failed to read KB entry {md_file}: {e}\n"
                            "Guru Meditation: #SA.00000002.KBREAD\n"
                            "Check: File permissions and encoding"
                        ) from e

                    entries.append(
                        RecentEntry(
                            title=title,
                            path=str(md_file.relative_to(kb_path)),
                            created_at=mtime,
                        )
                    )

            # Sort by recency
            entries.sort(key=lambda e: e.created_at, reverse=True)

        except Exception as e:
            raise RuntimeError(
                f"Failed to scan KB for recent entries: {e}\n"
                "Guru Meditation: #SA.00000003.KBSCAN\n"
                "Check: KB path exists and is accessible"
            ) from e

        return entries

    async def _count_kb_entries(self) -> int:
        """Count total KB entries."""
        config = get_config()
        kb_path = config.kb.current_path

        if not kb_path.exists():
            return 0

        try:
            return sum(1 for _ in kb_path.rglob("*.md"))
        except Exception as e:
            raise RuntimeError(
                f"Failed to count KB entries: {e}\n"
                "Guru Meditation: #SA.00000004.KBCOUNT\n"
                "Check: KB path permissions"
            ) from e

    async def _count_vector_store(self) -> int:
        """Count vectors in Qdrant."""
        try:
            from qdrant_client import QdrantClient

            config = get_config()
            client = QdrantClient(
                host=config.vector_store.host,
                port=config.vector_store.port,
            )

            info = client.get_collection(config.vector_store.collection)
            return info.points_count or 0

        except Exception as e:
            raise RuntimeError(
                f"Failed to count vectors in Qdrant: {e}\n"
                "Guru Meditation: #SA.00000005.QDRANT\n"
                "Check: /health qdrant"
            ) from e

    def _extract_topics(self, titles: list[str]) -> list[str]:
        """Extract key topics from titles using simple frequency."""
        from collections import Counter

        # Common stop words
        stop_words = {
            "the", "a", "an", "and", "or", "but", "in", "on", "at", "to",
            "for", "of", "with", "by", "from", "as", "is", "was", "are",
            "were", "been", "be", "have", "has", "had", "do", "does", "did",
            "will", "would", "could", "should", "may", "might", "must", "can",
            "this", "that", "these", "those", "it", "its", "their", "them",
        }

        words = []
        for title in titles:
            for word in title.lower().split():
                word = word.strip(".,!?()[]{}:;\"'")
                if len(word) > 3 and word not in stop_words:
                    words.append(word)

        counter = Counter(words)
        return [word for word, _ in counter.most_common(10)]

    async def _generate_insights(self, report: SituationalReport) -> list[str]:
        """Generate insights using LLM."""
        insights = []

        # Basic heuristic insights (no LLM needed)
        if report.emphasis and report.emphasis.entry_count > 10:
            insights.append(
                f"High activity: {report.emphasis.entry_count} entries in the last "
                f"{self.config.emphasis_hours} hours"
            )

        if report.activity_today and report.activity_today.swarm_runs > 3:
            insights.append(
                f"Heavy swarm usage: {report.activity_today.swarm_runs} runs today, "
                f"{report.activity_today.total_tokens:,} tokens"
            )

        if report.activity_week and report.activity_week.total_events > 100:
            insights.append("Very active week with significant KB growth")

        # Try LLM synthesis if available and we have data
        if report.emphasis and report.emphasis.notable_entries:
            try:
                from gaius.client import get_grpc_client

                client = await get_grpc_client()

                # Build context from recent entries
                entry_list = "\n".join(
                    f"- {e.title}" for e in report.emphasis.notable_entries[:5]
                )

                result = await client.call(
                    service="Scheduler",
                    action="complete",
                    params={
                        "prompt": f"""Based on these recent KB entries, provide 2-3 brief insights (one sentence each):

{entry_list}

Focus on patterns, connections, or areas needing attention.""",
                        "agent": "thinking",
                        "max_tokens": 200,
                        "temperature": 0.5,
                    },
                )

                # Parse response into insights
                for line in result.get("content", "").split("\n"):
                    line = line.strip().lstrip("-•*").strip()
                    if line and len(line) > 10:
                        insights.append(line)

            except Exception as e:
                raise RuntimeError(
                    f"Failed to generate LLM insights: {e}\n"
                    "Guru Meditation: #SA.00000006.LLMINSIGHT\n"
                    "Check: /health endpoints"
                ) from e

        return insights[:5]

    async def _generate_focus(self, report: SituationalReport) -> str | None:
        """Generate recommended focus area."""
        if not report.emphasis or not report.emphasis.key_topics:
            return None

        topics = ", ".join(report.emphasis.key_topics[:3])
        return f"Current emphasis areas: {topics}"


# Module-level singleton
_awareness: SituationalAwareness | None = None


def get_situational_awareness() -> SituationalAwareness:
    """Get or create situational awareness singleton."""
    global _awareness
    if _awareness is None:
        _awareness = SituationalAwareness()
    return _awareness


async def generate_startup_report(
    profile: str = "default",
    domain: str | None = None,
    include_insights: bool = True,
) -> SituationalReport:
    """Convenience function to generate startup report."""
    awareness = get_situational_awareness()
    return await awareness.generate_report(
        profile=profile,
        current_domain=domain,
        include_insights=include_insights,
    )
