"""Gunicorn configuration generator for optillm.

Generates gunicorn configuration files dynamically based on engine settings.
Supports runtime reconfiguration via SIGHUP signal.
"""

import logging
import os
import tempfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


@dataclass
class GunicornSettings:
    """Settings for gunicorn WSGI server."""

    # Binding
    bind: str = "127.0.0.1:8000"

    # Workers
    workers: int = 4
    worker_class: str = "gthread"
    threads: int = 2
    timeout: int = 120
    graceful_timeout: int = 30
    keepalive: int = 5

    # Request handling
    max_requests: int = 1000
    max_requests_jitter: int = 50

    # Logging
    loglevel: str = "info"
    accesslog: str = "-"
    errorlog: str = "-"

    # Process
    proc_name: str = "optillm-gunicorn"
    daemon: bool = False

    # Environment for optillm
    optillm_api_key: str = ""
    optillm_approach: str = "none"
    optillm_base_url: str = ""

    # Generated paths
    pidfile: Optional[str] = None
    config_dir: str = "/tmp/gaius"


# Template for gunicorn.conf.py
GUNICORN_CONFIG_TEMPLATE = '''# -*- coding: utf-8 -*-
"""Gunicorn configuration for optillm.

Generated by gaius engine at {generated_at}
DO NOT EDIT - regenerated on each start/reload
"""

# Server socket
bind = "{bind}"
backlog = 2048

# Worker processes
workers = {workers}
worker_class = "{worker_class}"
threads = {threads}
timeout = {timeout}
graceful_timeout = {graceful_timeout}
keepalive = {keepalive}

# Request handling
max_requests = {max_requests}
max_requests_jitter = {max_requests_jitter}

# Server mechanics
daemon = {daemon}
pidfile = {pidfile_repr}

# Logging
errorlog = "{errorlog}"
loglevel = "{loglevel}"
accesslog = "{accesslog}"

# Process naming
proc_name = "{proc_name}"

# Environment variables for optillm
# NOTE: Do NOT set OPTILLM_API_KEY - that triggers local inference mode which
# tries to load model tokenizers. Instead, set OPENAI_API_KEY to use the
# OpenAI-compatible proxy path with base_url.
raw_env = [
    "OPENAI_API_KEY={optillm_api_key}",
    "OPTILLM_APPROACH={optillm_approach}",
    "OPTILLM_BASE_URL={optillm_base_url}",
    # Deep reasoning is the product: keep cot_reflection's <thinking>/<reflection>
    # scaffold in the response so callers (article-curate select_article → HX
    # hx.cot_reasoning) retain the trace. Default optillm returns ONLY <output>.
    "OPTILLM_RETURN_FULL_RESPONSE=true",
]


def when_ready(server):
    """Called when the server is ready to accept connections."""
    print(f"[optillm-gunicorn] Server ready at {bind}")


def on_starting(server):
    """Called before the master process is initialized."""
    print("[optillm-gunicorn] Starting server...")


def on_reload(server):
    """Called during reload."""
    print("[optillm-gunicorn] Reloading configuration...")


def worker_int(worker):
    """Called when a worker receives SIGINT."""
    print(f"[optillm-gunicorn] Worker {{worker.pid}} interrupted")


def worker_abort(worker):
    """Called when a worker receives SIGABRT."""
    print(f"[optillm-gunicorn] Worker {{worker.pid}} aborted")


def post_fork(server, worker):
    """Called after a worker is forked - configure optillm server_config from env vars.

    This is necessary because optillm only reads OPTILLM_BASE_URL in main(),
    which is not called when running via gunicorn.
    """
    import os
    import sys
    try:
        from optillm import server as optillm_server

        # Patch server_config with environment variables
        base_url = os.environ.get("OPTILLM_BASE_URL", "")
        api_key = os.environ.get("OPENAI_API_KEY", "")  # Use OPENAI_API_KEY, not OPTILLM_API_KEY
        approach = os.environ.get("OPTILLM_APPROACH", "none")

        # Debug: write to file to verify hook runs
        with open("/tmp/gaius/optillm_postfork.log", "a") as f:
            f.write(f"post_fork: pid={{worker.pid}} base_url={{base_url}} api_key={{api_key}} approach={{approach}}\\n")

        if base_url:
            optillm_server.server_config["base_url"] = base_url
            print(f"[optillm-gunicorn] Worker {{worker.pid}} configured base_url={{base_url}}", file=sys.stderr)

        if api_key:
            optillm_server.server_config["optillm_api_key"] = api_key
            print(f"[optillm-gunicorn] Worker {{worker.pid}} configured api_key={{api_key}}", file=sys.stderr)

        if approach:
            optillm_server.server_config["approach"] = approach

        # return_full_response is CLI/main()-only in optillm; patch it from env so
        # cot_reflection keeps its <thinking>/<reflection> scaffold (the trace).
        full = os.environ.get("OPTILLM_RETURN_FULL_RESPONSE", "").strip().lower()
        if full in ("1", "true", "yes", "on"):
            optillm_server.server_config["return_full_response"] = True
            print(f"[optillm-gunicorn] Worker {{worker.pid}} return_full_response=True", file=sys.stderr)

        # Re-initialize the OpenAI client with the correct base_url
        if base_url:
            from openai import OpenAI
            optillm_server.default_client = OpenAI(api_key=api_key or "dummy", base_url=base_url)
            print(f"[optillm-gunicorn] Worker {{worker.pid}} initialized OpenAI client with base_url={{base_url}}", file=sys.stderr)

    except Exception as e:
        print(f"[optillm-gunicorn] Worker {{worker.pid}} config error: {{e}}")
'''


class GunicornConfigGenerator:
    """Generates gunicorn configuration files for optillm.

    Creates and manages gunicorn.conf.py files in a temp directory.
    Supports regeneration for SIGHUP-based reloads.
    """

    def __init__(
        self,
        settings: GunicornSettings | None = None,
        config_dir: str | Path | None = None,
    ):
        """Initialize the config generator.

        Args:
            settings: GunicornSettings instance. If None, uses defaults.
            config_dir: Directory for config files. Defaults to /tmp/gaius.
        """
        self.settings = settings or GunicornSettings()

        # Resolve config directory
        if config_dir:
            self._config_dir = Path(config_dir)
        else:
            self._config_dir = Path(self.settings.config_dir)

        self._config_path: Optional[Path] = None
        self._pidfile_path: Optional[Path] = None
        self._last_generated: Optional[datetime] = None

    @property
    def config_path(self) -> Path:
        """Path to the generated gunicorn.conf.py."""
        if self._config_path is None:
            self._ensure_config_dir()
            self._config_path = self._config_dir / "gunicorn_optillm.conf.py"
        return self._config_path

    @property
    def pidfile_path(self) -> Path:
        """Path to the gunicorn PID file."""
        if self._pidfile_path is None:
            self._ensure_config_dir()
            self._pidfile_path = self._config_dir / "optillm.pid"
        return self._pidfile_path

    def _ensure_config_dir(self) -> None:
        """Ensure config directory exists."""
        self._config_dir.mkdir(parents=True, exist_ok=True)

    def generate(self) -> Path:
        """Generate the gunicorn configuration file.

        Returns:
            Path to the generated config file.
        """
        self._ensure_config_dir()

        # Update pidfile in settings
        self.settings.pidfile = str(self.pidfile_path)

        # Generate config content
        content = GUNICORN_CONFIG_TEMPLATE.format(
            generated_at=datetime.now().isoformat(),
            bind=self.settings.bind,
            workers=self.settings.workers,
            worker_class=self.settings.worker_class,
            threads=self.settings.threads,
            timeout=self.settings.timeout,
            graceful_timeout=self.settings.graceful_timeout,
            keepalive=self.settings.keepalive,
            max_requests=self.settings.max_requests,
            max_requests_jitter=self.settings.max_requests_jitter,
            daemon="True" if self.settings.daemon else "False",
            pidfile_repr=repr(self.settings.pidfile),
            errorlog=self.settings.errorlog,
            loglevel=self.settings.loglevel,
            accesslog=self.settings.accesslog,
            proc_name=self.settings.proc_name,
            optillm_api_key=self.settings.optillm_api_key,
            optillm_approach=self.settings.optillm_approach,
            optillm_base_url=self.settings.optillm_base_url,
        )

        # Write atomically via temp file + rename
        temp_path = self.config_path.with_suffix(".tmp")
        temp_path.write_text(content)
        temp_path.rename(self.config_path)

        self._last_generated = datetime.now()
        logger.info(f"Generated gunicorn config: {self.config_path}")

        return self.config_path

    def update_settings(self, **kwargs: Any) -> None:
        """Update settings and regenerate config.

        Args:
            **kwargs: Settings to update (e.g., workers=2, timeout=60).
        """
        for key, value in kwargs.items():
            if hasattr(self.settings, key):
                setattr(self.settings, key, value)
                logger.debug(f"Updated gunicorn setting: {key}={value}")
            else:
                logger.warning(f"Unknown gunicorn setting: {key}")

    def update_workers(self, count: int) -> Path:
        """Update worker count and regenerate config.

        Args:
            count: New worker count.

        Returns:
            Path to regenerated config.
        """
        self.settings.workers = count
        return self.generate()

    def update_technique(self, technique: str) -> Path:
        """Update default technique and regenerate config.

        Args:
            technique: New default technique (e.g., "cot_reflection", "bon").

        Returns:
            Path to regenerated config.
        """
        self.settings.optillm_approach = technique
        return self.generate()

    def cleanup(self) -> None:
        """Remove generated config files."""
        if self._config_path and self._config_path.exists():
            self._config_path.unlink()
            logger.debug(f"Removed config: {self._config_path}")

        if self._pidfile_path and self._pidfile_path.exists():
            self._pidfile_path.unlink()
            logger.debug(f"Removed pidfile: {self._pidfile_path}")

    def get_command_args(self) -> list[str]:
        """Get gunicorn command line arguments.

        Returns:
            List of arguments for subprocess.
        """
        return [
            "--config",
            str(self.config_path),
            "optillm.server:app",
        ]

    def get_status(self) -> dict[str, Any]:
        """Get current configuration status.

        Returns:
            Dict with config paths and settings.
        """
        return {
            "config_path": str(self.config_path) if self._config_path else None,
            "pidfile_path": str(self.pidfile_path) if self._pidfile_path else None,
            "last_generated": (
                self._last_generated.isoformat() if self._last_generated else None
            ),
            "settings": {
                "bind": self.settings.bind,
                "workers": self.settings.workers,
                "worker_class": self.settings.worker_class,
                "threads": self.settings.threads,
                "timeout": self.settings.timeout,
                "technique": self.settings.optillm_approach,
            },
        }
