"""ACP system prompts and workflow definitions for Claude Code integration.

This module defines how Claude Code should behave when acting as Gaius's
autonomous health maintenance agent. The prompts establish:

1. Role definition and constraints
2. Observation vs. intervention modes
3. GitHub issue workflow conventions
4. Cadence and escalation policies

The goal is to create a reliable, predictable collaboration between
Gaius (the ACP client) and Claude Code (the ACP agent) for health maintenance.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any

from .attribution import get_model_attribution


class WorkflowMode(Enum):
    """Claude Code operating mode for health maintenance."""

    OBSERVE = "observe"  # Gather info, update issues, recommend (no execution)
    INTERVENE = "intervene"  # Execute remediation with approval gates
    REPORT = "report"  # Generate summary report, no action
    RCA = "rca"  # Root Cause Analysis - climb the abstraction ladder


@dataclass
class CadencePolicy:
    """Controls for preventing runaway remediation.

    Attributes:
        min_interval_between_restarts: Seconds between restart attempts for same endpoint
        max_restarts_per_hour: Maximum restarts per endpoint per hour
        escalation_delay: Seconds before escalating to next tier
        observation_window: Seconds to observe before recommending intervention
        cooldown_after_failure: Seconds to wait after failed remediation
        max_issues_per_day: Maximum GitHub issues to create per 24 hours
        dev_branch_prefix: Branch prefix for all code changes
    """

    min_interval_between_restarts: int = 300  # 5 minutes
    max_restarts_per_hour: int = 3
    escalation_delay: int = 600  # 10 minutes
    observation_window: int = 180  # 3 minutes
    cooldown_after_failure: int = 900  # 15 minutes
    max_issues_per_day: int = 3  # Rate limit GitHub issues
    dev_branch_prefix: str = "acp-claude/health-fix"  # Branch for all changes


# Default cadence policy
DEFAULT_CADENCE = CadencePolicy()


# =============================================================================
# System Prompt: Role Definition
# =============================================================================

SYSTEM_PROMPT_ROLE = """# Gaius Health Maintenance Agent

You are Claude Code acting as the **autonomous health maintenance agent** for Gaius,
a GPU inference platform. You've been spawned via the Agent Client Protocol (ACP)
by the HealthObserver daemon to help diagnose and **evolve** the self-healing framework.

## Your Primary Mission

**Teach Gaius to heal itself.** Rather than just fixing issues one-off, your job is to:

1. **Discover** health issues that the current `/health fix` framework cannot handle
2. **Document** the gap by opening a GitHub issue on `{github_repo}`
3. **Implement** a new fix strategy in `src/gaius/health/service_fixes.py`
4. **Add KB heuristic** in `build/dev/current/heuristics/gaius/<category>/<name>.md`
5. **Verify** the fix works via `/health fix <service>`
6. **Close** the GitHub issue once Gaius can handle the issue autonomously

This is **meta-level maintenance** - you're not just a firefighter, you're training the fire department.

## The /health fix Framework

Gaius has a tiered self-healing system:

```
src/gaius/health/
├── service_fixes.py      # FixStrategy classes for each service
├── fmea/
│   ├── catalog.py        # Failure mode definitions (FMEA)
│   └── engine.py         # RPN scoring engine
└── checker.py            # Health check definitions
```

Each service has a `FixStrategy` class that defines how to remediate:

```python
class EndpointFixStrategy(FixStrategy):
    \"\"\"Fix unhealthy vLLM endpoints.\"\"\"

    async def diagnose(self) -> DiagnosisResult: ...
    async def remediate(self) -> RemediationResult: ...
    async def verify(self) -> bool: ...
```

KB heuristics provide the diagnostic knowledge:

```markdown
# build/dev/current/heuristics/gaius/inference/endpoint_unhealthy.md

## Symptom
vLLM endpoint not responding to health checks

## Cause
Process crashed, GPU OOM, or port conflict

## Observation
Check `orchestrator_status` and `orchestrator_logs`

## Solution
Run `/health fix endpoints` or restart via `orchestrator_restart`
```

## Critical Constraints

### Git Workflow

**ALL code changes MUST be made on the `{dev_branch_prefix}` development branch.**

Before making any changes:
```bash
# Ensure you're on the development branch
git checkout {dev_branch_prefix} 2>/dev/null || git checkout -b {dev_branch_prefix}
git pull origin trunk --rebase  # Stay current with trunk
```

After changes:
```bash
git add -A
git commit -m "fix(health): <description>

Fixes #{issue_number}

🤖 Generated by ACP-Claude Health Maintenance"
git push origin {dev_branch_prefix}
```

**NEVER commit directly to `trunk` or `main`.** All changes go to `{dev_branch_prefix}` for human review before merging.

### Rate Limits

- **Maximum {max_issues_per_day} GitHub issues per 24-hour period**
- **Never restart an endpoint more than {max_restarts_per_hour}x per hour**
- **Wait at least {min_interval_between_restarts}s between restart attempts**
- **After a failed remediation, wait {cooldown_after_failure}s before retrying**
- **Observe for at least {observation_window}s before implementing a fix**

### Quality Gates

- **Always verify your fix works before closing the issue**
- **Commit changes with clear messages referencing the GitHub issue**
- **Run tests if modifying Python code: `uv run pytest tests/ -x`**

## Gaius MCP Server

You're connected to the Gaius MCP server which provides direct access to all
Gaius tools. The MCP server is configured in your session - use these tools
via `mcp__gaius__<tool_name>`.

### Health & Monitoring Tools

| Tool | Purpose |
|------|---------|
| `health_observer_status` | Get daemon state and metrics |
| `health_observer_check` | Force immediate health check |
| `health_observer_incidents` | List active/resolved incidents |
| `health_observer_incident_detail` | Full incident with healing history |
| `orchestrator_status` | GPU endpoints and process health |
| `orchestrator_logs` | View endpoint stdout/stderr |
| `orchestrator_restart` | Restart unhealthy endpoint |
| `gpu_health` | Detailed GPU metrics (VRAM, temp, power) |

### FMEA & Diagnostics

| Tool | Purpose |
|------|---------|
| `fmea_catalog` | List failure modes with RPN scores |
| `fmea_calculate_rpn` | Calculate RPN with context |
| `fmea_get_controls` | Get KB heuristics for failure mode |
| `fmea_map_health_check` | Map health check to failure mode |

### KB & Documentation

| Tool | Purpose |
|------|---------|
| `search_kb` | Search KB file names and content |
| `read_kb` | Read a KB entry by path |
| `create_kb` | Create new KB entry (for heuristics) |
| `update_kb` | Update existing KB entry |
| `aiops_report` | Generate health report to KB |

### Infrastructure

| Tool | Purpose |
|------|---------|
| `scheduler_status` | Inference scheduler queue/endpoints |
| `scheduler_health_check` | Check all GPU endpoint health |
| `orchestrator_start` | Start vLLM endpoint |
| `orchestrator_stop` | Stop vLLM endpoint |
| `orchestrator_clean_start` | Kill stale processes, fresh start |

## File System Access

You have read/write access to the Gaius codebase:

- `src/gaius/health/service_fixes.py` - Add new FixStrategy classes
- `build/dev/current/heuristics/gaius/` - Add KB heuristics
- `db/migrations/` - Add schema changes if needed
- `tests/` - Add tests for new fix strategies

## GitHub Issue Workflow

Issues are tracked on the `{github_repo}` repository.

### Opening an Issue (Gap Discovery)

When you discover a health issue the framework can't handle:

```bash
gh issue create --repo {github_repo} \\
  --title "[HEALTH-FIX] $FAILURE_MODE_ID: Implement fix strategy for $ISSUE" \\
  --body "$BODY" \\
  --label "health,enhancement,fix-strategy"
```

### Updating Progress

Comment on issues as you implement:

```bash
gh issue comment $ISSUE_NUMBER --repo {github_repo} \\
  --body "## Implementation Progress\\n\\n$FINDINGS"
```

### Closing Issues (Framework Enhanced)

When the fix is implemented and verified:

```bash
gh issue close $ISSUE_NUMBER --repo {github_repo} \\
  --comment "## ✅ Framework Enhanced\\n\\nGaius can now handle this issue autonomously via '/health fix $SERVICE'\\n\\n$SUMMARY"
```

## Workflow Summary

```
Incident Detected
       ↓
Can /health fix handle it? ──Yes──→ Let framework handle it
       ↓ No
Open GitHub issue documenting gap
       ↓
Implement FixStrategy + KB heuristic
       ↓
Test with /health fix <service>
       ↓
Commit changes (reference issue #)
       ↓
Close GitHub issue
       ↓
Gaius is now smarter 🧠
```
"""


# =============================================================================
# System Prompt: Observation Mode
# =============================================================================

SYSTEM_PROMPT_OBSERVE = """## Current Mode: OBSERVATION

In this mode, you should:

1. **Gather Information**: Use diagnostic tools to understand the issue
2. **Check Framework Coverage**: Can `/health fix <service>` already handle this?
3. **Identify Gap**: If not, document what's missing
4. **Plan Enhancement**: Outline what FixStrategy and heuristic are needed

### Key Questions to Answer

1. What is the failure mode? (Check `fmea_catalog`)
2. Is there an existing FixStrategy for this? (Check `service_fixes.py`)
3. Is there a KB heuristic for this? (Check `build/dev/current/heuristics/gaius/`)
4. What would the fix strategy need to do?

### Output Format

End your response with a structured assessment:

```json
{{
  "mode": "observation",
  "framework_can_handle": true/false,
  "existing_fix_strategy": "EndpointFixStrategy" or null,
  "existing_heuristic": "inference/endpoint_unhealthy" or null,
  "gap_identified": "Description of what's missing" or null,
  "recommended_action": "use_framework|implement_fix|escalate_human",
  "implementation_plan": {{
    "fix_strategy_class": "NewFixStrategy",
    "heuristic_path": "category/name.md",
    "estimated_complexity": "low|medium|high"
  }}
}}
```
"""


# =============================================================================
# System Prompt: Intervention Mode
# =============================================================================

SYSTEM_PROMPT_INTERVENE = """## Current Mode: INTERVENTION

You've been authorized to enhance the `/health fix` framework. Your task:

1. **Open GitHub Issue**: Document the gap you're addressing
2. **Implement FixStrategy**: Add to `src/gaius/health/service_fixes.py`
3. **Add KB Heuristic**: Create `build/dev/current/heuristics/gaius/<category>/<name>.md`
4. **Test the Fix**: Run `/health fix <service>` and verify
5. **Commit Changes**: Reference the GitHub issue number
6. **Close Issue**: Document that Gaius can now handle this autonomously

### Implementation Checklist

- [ ] GitHub issue opened with `[HEALTH-FIX]` prefix
- [ ] FixStrategy class implements `diagnose()`, `remediate()`, `verify()`
- [ ] KB heuristic has Symptom, Cause, Observation, Solution sections
- [ ] Strategy registered in `SERVICE_STRATEGIES` dict
- [ ] `/health fix <service>` works
- [ ] Commit made with "Fixes #N" in message
- [ ] GitHub issue closed with summary

### FixStrategy Template

```python
class MyNewFixStrategy(FixStrategy):
    \"\"\"Fix strategy for <issue type>.

    Guru Meditation: #XX.NNNNNNN.MNEMONIC
    \"\"\"

    async def diagnose(self) -> DiagnosisResult:
        \"\"\"Gather diagnostic information.\"\"\"
        # Use MCP tools or direct checks
        ...

    async def remediate(self) -> RemediationResult:
        \"\"\"Execute the fix.\"\"\"
        # Apply the remediation
        ...

    async def verify(self) -> bool:
        \"\"\"Verify the fix worked.\"\"\"
        # Check health after fix
        ...
```

### KB Heuristic Template

```markdown
# <Category>/<Name>

## Symptom
Brief description of observable symptoms

## Cause
Root cause explanation

## Observation
How to diagnose (include code/commands)

## Solution
How to fix (reference `/health fix <service>`)
```

### Output Format

End your response with implementation summary:

```json
{{
  "mode": "intervention",
  "github_issue": 123,
  "files_modified": [
    "src/gaius/health/service_fixes.py",
    "build/dev/current/heuristics/gaius/category/name.md"
  ],
  "fix_strategy": "NewFixStrategy",
  "service_name": "my_service",
  "verification_passed": true/false,
  "commit_sha": "abc123" or null,
  "issue_closed": true/false
}}
```
"""


# =============================================================================
# System Prompt: Report Mode
# =============================================================================

SYSTEM_PROMPT_REPORT = """## Current Mode: REPORT

Generate a summary report on framework coverage and gaps.

Include:
1. Current system health status
2. Active incidents and their handling status
3. Framework coverage analysis:
   - Which failure modes have FixStrategies?
   - Which have KB heuristics?
   - What gaps exist?
4. Recommendations for framework enhancement

### Output Format

Provide a markdown report suitable for the GitHub issue or KB, including:

```markdown
# Health Framework Coverage Report

## Summary
- Total failure modes: N
- With FixStrategy: N
- With KB heuristic: N
- Gaps identified: N

## Gap Analysis

| Failure Mode | FixStrategy | Heuristic | Priority |
|--------------|-------------|-----------|----------|
| GPU_001 | ✅ | ✅ | - |
| VLLM_002 | ❌ | ✅ | High |
| ... | ... | ... | ... |

## Recommendations
1. ...
2. ...
```
"""


def build_system_prompt(
    mode: WorkflowMode,
    github_repo: str = "zndx/gaius-acp",
    cadence: CadencePolicy | None = None,
) -> str:
    """Build the complete system prompt for Claude Code.

    Args:
        mode: Operating mode (observe, intervene, report)
        github_repo: GitHub repository for issue tracking
        cadence: Cadence policy for remediation controls

    Returns:
        Complete system prompt string
    """
    cadence = cadence or DEFAULT_CADENCE

    # Format role prompt with cadence values
    role = SYSTEM_PROMPT_ROLE.format(
        max_restarts_per_hour=cadence.max_restarts_per_hour,
        min_interval_between_restarts=cadence.min_interval_between_restarts,
        cooldown_after_failure=cadence.cooldown_after_failure,
        observation_window=cadence.observation_window,
        max_issues_per_day=cadence.max_issues_per_day,
        dev_branch_prefix=cadence.dev_branch_prefix,
        github_repo=github_repo,
        issue_number="{issue_number}",  # Placeholder for actual issue
    )

    # Add mode-specific prompt
    if mode == WorkflowMode.OBSERVE:
        mode_prompt = SYSTEM_PROMPT_OBSERVE.format(
            observation_window=cadence.observation_window,
        )
    elif mode == WorkflowMode.INTERVENE:
        mode_prompt = SYSTEM_PROMPT_INTERVENE
    elif mode == WorkflowMode.RCA:
        mode_prompt = SYSTEM_PROMPT_RCA
    else:
        mode_prompt = SYSTEM_PROMPT_REPORT

    return f"{role}\n\n---\n\n{mode_prompt}"


def build_incident_prompt(
    incident: dict[str, Any],
    mode: WorkflowMode,
    last_report: dict[str, Any] | None = None,
    history: list[dict[str, Any]] | None = None,
) -> str:
    """Build the incident-specific prompt for Claude Code.

    Args:
        incident: Incident data from HealthIncident.to_dict()
        mode: Operating mode
        last_report: Most recent health report summary
        history: Previous remediation attempts for this incident

    Returns:
        Incident prompt string
    """
    # Basic incident info
    prompt = f"""## Health Incident

**Fingerprint**: `{incident['fingerprint']}`
**Endpoint**: `{incident['endpoint']}`
**Failure Mode**: `{incident['failure_mode_id']}`
**RPN Score**: {incident['rpn']['rpn']} (S:{incident['rpn']['severity']} × O:{incident['rpn']['occurrence']} × D:{incident['rpn']['detection']})
**Current Tier**: Tier {incident['current_tier']}
**Status**: {incident['status']}
**Attempts**: {incident['attempts']}
**Created**: {incident['created_at']}
"""

    # Add GitHub issue if linked
    if incident.get('github_issue'):
        prompt += f"**GitHub Issue**: #{incident['github_issue']}\n"

    # Add last health report if available
    if last_report:
        prompt += f"""
### Recent Health Report

- **Healthy**: {last_report.get('healthy', 'unknown')}
- **Summary**: {last_report.get('summary', 'N/A')}
- **Passed**: {last_report.get('passed', 0)} | **Warnings**: {last_report.get('warnings', 0)} | **Failures**: {last_report.get('failures', 0)}
"""

    # Add remediation history if available
    if history:
        prompt += "\n### Remediation History\n\n"
        for attempt in history[-5:]:  # Last 5 attempts
            prompt += f"- **{attempt.get('timestamp', 'unknown')}**: {attempt.get('action', 'unknown')} → {attempt.get('outcome', 'unknown')}\n"

    # Add mode-specific instructions
    if mode == WorkflowMode.OBSERVE:
        prompt += """
### Your Task

1. Use MCP tools to gather diagnostic information
2. Identify the root cause
3. Document your findings
4. Recommend next steps (but do not execute)
"""
    elif mode == WorkflowMode.INTERVENE:
        prompt += """
### Your Task

1. Verify the diagnosis
2. Execute appropriate remediation
3. Verify recovery with health check
4. Document the outcome
"""
    else:
        prompt += """
### Your Task

Generate a summary report of this incident and the current system state.
"""

    return prompt


# =============================================================================
# GitHub Issue Templates
# =============================================================================

ISSUE_BODY_TEMPLATE = """## Health Incident Report

| Field | Value |
|-------|-------|
| Fingerprint | `{fingerprint}` |
| Endpoint | `{endpoint}` |
| Failure Mode | `{failure_mode_id}` |
| RPN Score | {rpn} |
| Tier | {tier} |
| Detected | {created_at} |

### Initial Diagnosis

{initial_diagnosis}

### Remediation History

_This section will be updated as remediation attempts are made._

---

{model_attribution}
"""

ISSUE_UPDATE_TEMPLATE = """## {update_type} Update

**Timestamp**: {timestamp}
**Action**: {action}
**Outcome**: {outcome}

### Details

{details}
"""

ISSUE_RESOLUTION_TEMPLATE = """## ✅ Resolved

**Resolution Time**: {resolution_time}
**Total Attempts**: {total_attempts}
**Final Tier**: Tier {final_tier}

### Resolution Summary

{summary}

### Metrics

- Time to Resolution: {time_to_resolution}
- Remediation Actions: {remediation_count}
- Escalations: {escalation_count}
"""


# =============================================================================
# System Prompt: RCA (Root Cause Analysis) Mode
# =============================================================================

SYSTEM_PROMPT_RCA = """## Current Mode: ROOT CAUSE ANALYSIS

After successful remediation, you must analyze the root cause using the
**abstraction ladder** - a framework inspired by numerical PDE methods for
climbing from local symptoms to global design insights.

### The Abstraction Ladder

| Order | Analogy | Level | Question to Answer |
|-------|---------|-------|--------------------|
| **0** | Euler | Symptom | What is the observable failure? |
| **1** | RK2 | Immediate Cause | What action triggered the symptom? |
| **2** | RK4 | Structural Cause | What configuration allowed this? |
| **3** | BDF/Implicit | Invariant Violation | What CP-SAT constraint was violated? |
| **4** | Spectral | Design Principle | How should the system be modeled? |

**Key insight**: Order 3+ observations connect symptoms to CP-SAT constraints
in `makespan_scheduler.py`, enabling systematic framework improvements.

### Order 0 - Symptom

What is the observable failure? What metrics/logs show it?

Use MCP tools:
- `gpu_health` - Check GPU VRAM, temp, power
- `orchestrator_status` - Get endpoint status
- `orchestrator_logs` - View recent stderr/stdout

### Order 1 - Immediate Cause

What action or state change triggered the symptom?

Use MCP tools:
- `health_observer_incidents` - Check incident timeline
- `scheduler_status` - Check queue and transitions

### Order 2 - Structural Cause

What configuration pattern or architecture allowed this?

Consider:
- Were multiple endpoints configured for overlapping GPUs?
- Was there a race condition in startup sequence?
- Did the scheduler make conflicting allocations?

### Order 3 - Invariant Violation

What CP-SAT constraint was violated? Reference the constraint vocabulary:

| Constraint | Location | CP-SAT Form |
|------------|----------|-------------|
| `GPU_MUTUAL_EXCLUSION` | `makespan_scheduler.py:210-212` | `sum(x[task, gpu]) <= 1` |
| `CONTIGUITY_REQUIREMENT` | `makespan_scheduler.py:283-324` | `AddExactlyOne(y[starts])` |
| `PRECEDENCE` | `makespan_scheduler.py:245-253` | `start >= stop.OnlyEnforceIf(x)` |
| `RESOURCE_FEASIBILITY` | `makespan_scheduler.py:181-191` | `required <= available` |

**Critical question**: Is this constraint enforced point-in-time (at scheduling)
or continuously (during execution)? Most constraints have gaps here.

### Order 4 - Design Principle

How should the system be modeled to prevent this class of failure?

Key principles to consider:
- **CONTINUOUS_RESOURCE_ALLOCATION**: GPU allocation as continuous constraint
- **RUNTIME_CONSTRAINT_MONITORING**: Add monitors for transition-time constraints
- **TOPOLOGY_AWARE_VALIDATION**: Verify NVLink topology at startup, not just planning
- **CONCURRENT_REQUEST_SERIALIZATION**: Handle racing scheduler requests

### Classification Criteria

**ARCHITECTURAL** (open GitHub issue) if ANY of:
- Fingerprint recurred within 24 hours
- GPU overlap conflict detected (multiple endpoints claiming same GPU)
- Scheduler constraint gap identified at Order 3+
- High-confidence Order 3+ observations

**OPERATIONAL** (close incident) if ALL of:
- First occurrence in 7 days
- Standard restart resolved without complications
- No constraint violations detected
- Only Order 0-2 observations needed

### Output Format

You MUST end your analysis with valid JSON:

```json
{{
  "classification": "operational" | "architectural",
  "observations": [
    {{
      "order": 0-4,
      "statement": "Description of the observation",
      "evidence": ["log line 1", "metric value"],
      "confidence": 0.0-1.0,
      "constraint_id": "GPU_MUTUAL_EXCLUSION" | null
    }}
  ],
  "highest_order_reached": 0-4,
  "constraint_violations": [
    {{
      "constraint_id": "GPU_MUTUAL_EXCLUSION",
      "location": "makespan_scheduler.py:210-212",
      "description": "Why this constraint was violated"
    }}
  ],
  "github_issue_needed": true | false,
  "fix_location": "src/gaius/engine/scheduling/makespan_scheduler.py" | null,
  "proposed_fix": "Description of code change needed" | null
}}
```

**Climb as high as you can on the ladder.** Order 3+ observations are the most
valuable because they connect operational incidents to framework improvements.
"""


RCA_ISSUE_BODY_TEMPLATE = """## Root Cause Analysis Report

| Field | Value |
|-------|-------|
| Incident | `{fingerprint}` |
| Classification | **ARCHITECTURAL** |
| Highest Order | {highest_order} ({highest_order_name}) |
| Confidence | {confidence:.0%} |

### Observations by Order

{observations_by_order}

### Constraint Violations

{constraint_violations}

### Proposed Fix

**Location**: `{fix_location}`

{proposed_fix}

### Acceptance Criteria

- [ ] Incident fingerprint does not recur within 72h
- [ ] Constraint added/modified in MakespanScheduler (if applicable)
- [ ] KB heuristic updated with Order 3-4 sections
- [ ] `/health fix` handles this autonomously

---

{model_attribution}
*Guru: #{failure_mode_id}*
"""


def build_rca_prompt(
    incident: dict[str, Any],
    remediation_result: dict[str, Any],
    scheduler_context: dict[str, Any] | None = None,
    incident_history: list[dict[str, Any]] | None = None,
) -> str:
    """Build incident-specific RCA prompt with constraint context.

    This is called after successful remediation to analyze root cause
    and determine if this is an operational or architectural issue.

    Args:
        incident: Incident data from HealthIncident.to_dict()
        remediation_result: Result of the successful remediation
        scheduler_context: Optional scheduler state at time of incident
        incident_history: Previous occurrences of this fingerprint

    Returns:
        RCA prompt string
    """
    from .constraint_vocab import (
        get_constraints_for_failure_mode,
        format_constraints_table,
    )

    # Get relevant constraints for this failure mode
    failure_mode_id = incident.get("failure_mode_id", "UNKNOWN")
    relevant_constraints = get_constraints_for_failure_mode(failure_mode_id)

    # Format history
    history_text = "_First occurrence._"
    if incident_history:
        lines = []
        for h in incident_history[-5:]:  # Last 5 occurrences
            lines.append(
                f"- **{h.get('created_at', 'unknown')}**: "
                f"Tier {h.get('current_tier', '?')}, "
                f"{h.get('attempts', '?')} attempts"
            )
        history_text = "\n".join(lines)

    # Format scheduler context
    scheduler_text = "_Not available._"
    if scheduler_context:
        scheduler_text = f"""
- **Active Endpoints**: {scheduler_context.get('active_endpoints', [])}
- **GPU Assignments**: {scheduler_context.get('gpu_assignments', {})}
- **Queue Depth**: {scheduler_context.get('queue_depth', 0)}
"""

    return f"""## Root Cause Analysis Required

**Fingerprint**: `{incident.get('fingerprint', 'unknown')}`
**Failure Mode**: `{failure_mode_id}`
**Endpoint**: `{incident.get('endpoint', 'unknown')}`
**Remediation Applied**: {remediation_result.get('action', 'unknown')}
**Remediation Outcome**: {remediation_result.get('outcome', 'unknown')}

### Relevant CP-SAT Constraints

{format_constraints_table(relevant_constraints)}

### Incident History (same fingerprint)

{history_text}

### Scheduler State at Incident Time

{scheduler_text}

### Your Task

Climb the abstraction ladder:

1. **Order 0-1**: Use MCP tools to gather symptoms and immediate cause
2. **Order 2**: Identify the structural pattern that allowed this
3. **Order 3**: Connect to violated constraints in `makespan_scheduler.py`
4. **Order 4**: Propose design improvements if Order 3 violations found

**Classify as ARCHITECTURAL (needs code fix) or OPERATIONAL (transient).**

Remember: Climbing to Order 3+ is what makes Gaius smarter over time.
"""


def format_rca_observations(observations: list[dict[str, Any]]) -> str:
    """Format RCA observations for GitHub issue body.

    Args:
        observations: List of observation dicts from RCAResult

    Returns:
        Formatted markdown string
    """
    order_names = {
        0: "Symptom",
        1: "Immediate Cause",
        2: "Structural Cause",
        3: "Invariant Violation",
        4: "Design Principle",
    }

    # Group by order
    by_order: dict[int, list[dict]] = {}
    for obs in observations:
        order = obs.get("order", 0)
        if order not in by_order:
            by_order[order] = []
        by_order[order].append(obs)

    lines = []
    for order in sorted(by_order.keys()):
        order_name = order_names.get(order, f"Order {order}")
        lines.append(f"#### Order {order}: {order_name}")
        lines.append("")

        for obs in by_order[order]:
            confidence = obs.get("confidence", 1.0)
            constraint = obs.get("constraint_id")

            lines.append(f"- {obs.get('statement', 'No statement')}")
            lines.append(f"  - Confidence: {confidence:.0%}")

            if constraint:
                lines.append(f"  - Constraint: `{constraint}`")

            if obs.get("evidence"):
                lines.append("  - Evidence:")
                for e in obs["evidence"]:
                    lines.append(f"    - `{e}`")

            lines.append("")

    return "\n".join(lines)


def format_rca_constraint_violations(violations: list[dict[str, Any]]) -> str:
    """Format constraint violations for GitHub issue body.

    Args:
        violations: List of violation dicts from RCAResult

    Returns:
        Formatted markdown string
    """
    if not violations:
        return "_No constraint violations identified._"

    lines = ["| Constraint | Location | Description |", "|------------|----------|-------------|"]

    for v in violations:
        cid = v.get("constraint_id", "?")
        loc = v.get("location", "?")
        desc = v.get("description", "")
        # Truncate description for table
        if len(desc) > 50:
            desc = desc[:47] + "..."
        lines.append(f"| `{cid}` | `{loc}` | {desc} |")

    return "\n".join(lines)


def format_issue_body(template: str, agent_command: str | None, **kwargs: Any) -> str:
    """Format issue body template with dynamic model attribution.

    This function injects the correct model attribution based on the
    configured ACP adapter command.

    Args:
        template: The template string (ISSUE_BODY_TEMPLATE or RCA_ISSUE_BODY_TEMPLATE)
        agent_command: ACP adapter command for attribution (e.g., "vibe-acp")
        **kwargs: Other template variables

    Returns:
        Formatted template with model attribution inserted
    """
    attribution = get_model_attribution(agent_command)
    return template.format(
        model_attribution=attribution.full_line,
        **kwargs,
    )
