-- Generated by `nautilus ddl --fdw` from src/store/ddl.rs — do not edit by hand.
-- Nautilus data product: foreign tables over signals_dataproducts.nautilus_* (Kudu tier0 +
-- the Impala logical views; see signals config/platform/nautilus-kudu.sql).
-- Apply to gaius :5444 AND signals :5455; impala_kudu_srv must exist (install_impala_fdw.sh).

-- nautilus_backlog: tier0 (Kudu, INSERT via kudu_scan) + the logical view (impala_sql)
DROP FOREIGN TABLE IF EXISTS nautilus_backlog CASCADE;
DROP FOREIGN TABLE IF EXISTS nautilus_backlog_tier0 CASCADE;

CREATE FOREIGN TABLE nautilus_backlog_tier0 (
  epoch_hour integer,
  ts_ns bigint,
  project text,
  workflow text,
  item_key text,
  slot smallint,
  state text,
  category text,
  first_miss_ns bigint,
  horizon_slot smallint,
  horizon_ns bigint,
  escalation_level smallint,
  resolved boolean,
  evidence text,
  spec_version text,
  engine_build text
) SERVER impala_kudu_srv OPTIONS (
  database 'signals_dataproducts', "table" 'nautilus_backlog_tier0',
  kudu_table 'impala::signals_dataproducts.nautilus_backlog_tier0', access 'kudu_scan');

CREATE FOREIGN TABLE nautilus_backlog (
  epoch_hour integer,
  ts_ns bigint,
  project text,
  workflow text,
  item_key text,
  slot smallint,
  state text,
  category text,
  first_miss_ns bigint,
  horizon_slot smallint,
  horizon_ns bigint,
  escalation_level smallint,
  resolved boolean,
  evidence text,
  spec_version text,
  engine_build text
) SERVER impala_kudu_srv OPTIONS (
  database 'signals_dataproducts', "table" 'nautilus_backlog', access 'impala_sql');

-- nautilus_events: tier0 (Kudu, INSERT via kudu_scan) + the logical view (impala_sql)
DROP FOREIGN TABLE IF EXISTS nautilus_events CASCADE;
DROP FOREIGN TABLE IF EXISTS nautilus_events_tier0 CASCADE;

CREATE FOREIGN TABLE nautilus_events_tier0 (
  epoch_hour integer,
  ts_ns bigint,
  project text,
  event_id text,
  kind text,
  trigger_name text,
  scope_name text,
  signature text,
  observer text,
  call_site text,
  proposition text,
  verdict text,
  p real,
  side_effect text,
  task_class text,
  task_id bigint,
  position_json text,
  directive_id text,
  forecast_id text,
  outcome_known boolean,
  outcome boolean,
  tier text,
  detail text,
  evidence text,
  spec_version text,
  engine_build text
) SERVER impala_kudu_srv OPTIONS (
  database 'signals_dataproducts', "table" 'nautilus_events_tier0',
  kudu_table 'impala::signals_dataproducts.nautilus_events_tier0', access 'kudu_scan');

CREATE FOREIGN TABLE nautilus_events (
  epoch_hour integer,
  ts_ns bigint,
  project text,
  event_id text,
  kind text,
  trigger_name text,
  scope_name text,
  signature text,
  observer text,
  call_site text,
  proposition text,
  verdict text,
  p real,
  side_effect text,
  task_class text,
  task_id bigint,
  position_json text,
  directive_id text,
  forecast_id text,
  outcome_known boolean,
  outcome boolean,
  tier text,
  detail text,
  evidence text,
  spec_version text,
  engine_build text
) SERVER impala_kudu_srv OPTIONS (
  database 'signals_dataproducts', "table" 'nautilus_events', access 'impala_sql');

-- nautilus_positions: tier0 (Kudu, INSERT via kudu_scan) + the logical view (impala_sql)
DROP FOREIGN TABLE IF EXISTS nautilus_positions CASCADE;
DROP FOREIGN TABLE IF EXISTS nautilus_positions_tier0 CASCADE;

CREATE FOREIGN TABLE nautilus_positions_tier0 (
  epoch_hour integer,
  ts_ns bigint,
  project text,
  process text,
  kind text,
  machine text,
  phase text,
  run_id text,
  step text,
  momentum bigint,
  source text,
  health text,
  silence_s integer,
  detail text
) SERVER impala_kudu_srv OPTIONS (
  database 'signals_dataproducts', "table" 'nautilus_positions_tier0',
  kudu_table 'impala::signals_dataproducts.nautilus_positions_tier0', access 'kudu_scan');

CREATE FOREIGN TABLE nautilus_positions (
  epoch_hour integer,
  ts_ns bigint,
  project text,
  process text,
  kind text,
  machine text,
  phase text,
  run_id text,
  step text,
  momentum bigint,
  source text,
  health text,
  silence_s integer,
  detail text
) SERVER impala_kudu_srv OPTIONS (
  database 'signals_dataproducts', "table" 'nautilus_positions', access 'impala_sql');
